version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/match4crisis-backend'
      - '/media:/var/www/media'
    ports:
      - '8000:8000'
    environment:
      - CI
      - TRAVIS
      - TRAVIS_PULL_REQUEST_SLUG
    env_file:
      - backend.prod.env
