# Generated by Django 3.0.7 on 2022-04-30 10:09

import apps.staff.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterApprovedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_code', models.IntegerField(default=apps.staff.models.random_number)),
                ('did_see_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_edited_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('frozen_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('send_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='', max_length=1000000)),
                ('was_sent', models.BooleanField(default=False)),
                ('send_to_organisations', models.BooleanField(default=False)),
                ('send_to_helpers', models.BooleanField(default=False)),
                ('send_to_refugees', models.BooleanField(default=False)),
                ('user_validation_required', models.IntegerField(choices=[(0, 'validierte'), (1, 'nicht validierte'), (2, 'validierte und nicht validierte'), (3, 'validiert und von uns approved')], default=0)),
                ('frozen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_newsletters', to=settings.AUTH_USER_MODEL)),
                ('letter_approved_by', models.ManyToManyField(related_name='approved_letters', through='staff.LetterApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('letter_authored_by', models.ManyToManyField(related_name='authored_letters', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_newsletters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='letterapprovedby',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Newsletter'),
        ),
        migrations.AddField(
            model_name='letterapprovedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='letterapprovedby',
            unique_together={('user', 'newsletter')},
        ),
    ]
