# Generated by Django 3.0.7 on 2022-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isHelper',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isOrganisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isRefugee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spokenLanguages',
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('HE', 'Helper'), ('RF', 'Refugee'), ('OR', 'Organization')], default='HE', max_length=2),
        ),
    ]
