# Generated by Django 3.0.7 on 2022-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220324_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.AddField(
            model_name='user',
            name='isHelper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isOrganisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isRefugee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='spokenLanguages',
            field=models.ManyToManyField(through='accounts.LanguageKnowledge', to='accounts.Languages'),
        ),
    ]
