# Generated by Django 3.0.7 on 2022-03-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220328_0702'),
        ('accounts', '0003_auto_20220323_2151'),
    ]

    operations = [
    ]
