# Generated by Django 3.0.7 on 2022-03-31 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20220331_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='spokenLanguages',
            field=models.ManyToManyField(blank=True, through='accounts.LanguageKnowledge', to='accounts.Languages'),
        ),
    ]
