# Generated by Django 3.0.7 on 2022-04-12 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_languages_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullName',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailValidationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email bestätigt am'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sharePhoneNumber',
            field=models.BooleanField(default=False, verbose_name='Telefonnummer teilen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='spokenLanguages',
            field=models.ManyToManyField(blank=True, through='accounts.LanguageKnowledge', to='accounts.Languages', verbose_name='Sprachkenntnisse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='validatedEmail',
            field=models.BooleanField(default=False, verbose_name='Email bestätigt'),
        ),
    ]
