# Generated by Django 3.0.7 on 2022-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220412_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Affiliated Country'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='englishName',
            field=models.CharField(max_length=128, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='isoCode',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO 639-1 Code'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='nativeName',
            field=models.CharField(max_length=128, verbose_name='Native Name'),
        ),
    ]
