# Generated by Django 3.0.7 on 2022-04-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220420_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NO', 'Keine Angabe'), ('FE', 'Weiblich'), ('MA', 'Männlich'), ('OT', 'Andere')], default='NO', max_length=2),
        ),
    ]
