# Generated by Django 3.0.7 on 2022-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastConfirmationMailSent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
