# Generated by Django 3.0.7 on 2022-03-20 17:17

import apps.offers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iofferhelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerType', models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation')], default='AC', max_length=2)),
                ('postCode', models.CharField(max_length=5)),
                ('streetName', models.CharField(max_length=200)),
                ('streetNumber', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
                ('offerDescription', models.TextField()),
                ('isDigital', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iofferhelp.Helper')),
                ('userId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationOffer',
            fields=[
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
                ('numberOfInhabitants', models.IntegerField()),
                ('petsAllowed', models.BooleanField(default=False)),
                ('streetName', models.CharField(blank=True, max_length=200)),
                ('streetNumber', models.CharField(blank=True, max_length=4)),
                ('stayLength', models.IntegerField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationOffer',
            fields=[
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
                ('firstLanguage', models.CharField(max_length=50)),
                ('secondLanguage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOffer',
            fields=[
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
                ('country', models.CharField(max_length=200)),
                ('postCodeEnd', models.CharField(max_length=5)),
                ('streetNameEnd', models.CharField(max_length=200)),
                ('streetNumberEnd', models.CharField(max_length=4)),
                ('typeOfCar', models.CharField(choices=[('LKW', 'Large Truck'), ('CAR', 'Car'), ('TRA', 'Transporter'), ('BUS', 'Bus')], default='CAR', max_length=3)),
                ('numberOfPassengers', models.IntegerField()),
                ('petsAllowed', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
