# Generated by Django 3.0.7 on 2022-03-18 13:01

import apps.offers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerType', models.CharField(max_length=200)),
                ('isDigital', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('postCodeStart', models.CharField(max_length=5, validators=[apps.offers.models.validate_plz])),
                ('streetNameStart', models.CharField(max_length=200)),
                ('streetNumberStart', models.CharField(max_length=4)),
                ('postCodeEnd', models.CharField(max_length=5, validators=[apps.offers.models.validate_plz])),
                ('streetNameEnd', models.CharField(max_length=200)),
                ('streetNumberEnd', models.CharField(max_length=4)),
                ('typeOfCar', models.CharField(choices=[('LKW', 'Large Truck'), ('CAR', 'Car'), ('TRA', 'Transporter'), ('BUS', 'Bus')], default='CAR', max_length=3)),
                ('numberOfPassengers', models.IntegerField()),
                ('petsAllowed', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.GenericOffer')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=5, validators=[apps.offers.models.validate_plz])),
                ('streetName', models.CharField(max_length=200)),
                ('streetNumber', models.CharField(max_length=4)),
                ('firstLanguage', models.CharField(max_length=50)),
                ('secondLanguage', models.CharField(max_length=50)),
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.GenericOffer')),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=5, validators=[apps.offers.models.validate_plz])),
                ('numberOfInhabitants', models.IntegerField()),
                ('petsAllowed', models.BooleanField(default=False)),
                ('streetName', models.CharField(max_length=200)),
                ('streetNumber', models.CharField(max_length=4)),
                ('stayLength', models.DurationField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('newGenericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.GenericOffer')),
            ],
        ),
    ]
