# Generated by Django 3.0.7 on 2022-03-18 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationoffer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='id',
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='newGenericOffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='stayLength',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='streetName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='streetNumber',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='newGenericOffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='newGenericOffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
        ),
    ]
