# Generated by Django 3.0.7 on 2022-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
        migrations.RenameField(
            model_name='translationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
        migrations.RenameField(
            model_name='transportationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
        migrations.RemoveField(
            model_name='accomodationoffer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='petsAllowed',
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
