# Generated by Django 3.0.7 on 2022-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20220318_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='offerDescription',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation')], default='AC', max_length=2),
        ),
    ]
