# Generated by Django 3.0.7 on 2022-03-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20220321_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericoffer',
            name='createdBy',
        ),
    ]
