# Generated by Django 3.0.7 on 2022-03-19 17:29

import apps.offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20220319_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationoffer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='accomodationoffer',
            name='postCode',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='postCode',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='streetNumber',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='postCodeStart',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='streetNameStart',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='streetNumberStart',
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='country',
            field=models.CharField(default='DE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='postCode',
            field=models.CharField(default=34431, max_length=5, validators=[apps.offers.models.validate_plz]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='streetName',
            field=models.CharField(default='Hermann-Hesse-Str.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='streetNumber',
            field=models.CharField(default=32, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='stayLength',
            field=models.IntegerField(blank=True),
        ),
    ]
