# Generated by Django 3.0.7 on 2022-03-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20220323_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericoffer',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-img.png', upload_to='users/%Y/%m/%d/')),
                ('offerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.GenericOffer')),
            ],
        ),
    ]
