# Generated by Django 3.0.7 on 2022-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20220319_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationoffer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='petsAllowed',
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
