# Generated by Django 3.0.7 on 2022-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20220324_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
