# Generated by Django 3.0.7 on 2022-03-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20220324_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageclass',
            old_name='id',
            new_name='image_id',
        ),
    ]
