# Generated by Django 3.0.7 on 2022-03-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20220320_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
        migrations.RenameField(
            model_name='translationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
        migrations.RenameField(
            model_name='transportationoffer',
            old_name='newGenericOffer',
            new_name='genericOffer',
        ),
    ]
