# Generated by Django 3.0.7 on 2022-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20220320_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
