# Generated by Django 3.0.7 on 2022-03-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20220323_1727'),
        ('offers', '0007_auto_20220324_0829'),
    ]

    operations = [
    ]
