# Generated by Django 3.0.7 on 2022-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_genericoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoffer',
            name='image',
            field=models.ImageField(default='no-img.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
