# Generated by Django 3.0.7 on 2022-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_remove_genericoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
