# Generated by Django 3.0.7 on 2022-03-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20220329_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericoffer',
            name='paused',
        ),
    ]
