# Generated by Django 3.0.7 on 2022-03-31 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_remove_genericoffer_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationoffer',
            name='numberOfInhabitants',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='stayLength',
            field=models.IntegerField(blank=True, default=14),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 7, 23, 26, 815483, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='numberOfPassengers',
            field=models.IntegerField(default=2),
        ),
    ]
