# Generated by Django 3.0.7 on 2022-04-01 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_auto_20220331_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanimentOffer',
            fields=[
                ('genericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 7, 12, 22, 507527, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('AP', 'Accompaniment')], default='AC', max_length=2),
        ),
    ]
