# Generated by Django 3.0.7 on 2022-04-01 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20220401_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 7, 21, 43, 151232, tzinfo=utc), verbose_name='date published'),
        ),
    ]
