# Generated by Django 3.0.7 on 2022-04-01 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_auto_20220401_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuerocraticOffer',
            fields=[
                ('genericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
                ('helpType', models.CharField(choices=[('AM', 'Accompaniment'), ('LE', 'Legal'), ('OT', 'Other')], default='AM', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 8, 34, 36, 761294, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic')], default='AC', max_length=2),
        ),
        migrations.DeleteModel(
            name='AccompanimentOffer',
        ),
        migrations.DeleteModel(
            name='LegalOffer',
        ),
    ]
