# Generated by Django 3.0.7 on 2022-04-01 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20220401_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpType', models.CharField(choices=[('ON', 'Online'), ('OS', 'On-site')], default='ON', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 9, 12, 21, 396863, tzinfo=utc), verbose_name='date published'),
        ),
    ]
