# Generated by Django 3.0.7 on 2022-04-01 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_auto_20220401_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpoweroffer',
            name='id',
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='genericOffer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 9, 19, 58, 10299, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower')], default='AC', max_length=2),
        ),
    ]
