# Generated by Django 3.0.7 on 2022-04-01 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_auto_20220401_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareOfferLongterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('NO', "Don't want to disclose"), ('FE', 'Female'), ('MA', 'Male')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChildcareOfferShortterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('NO', "Don't want to disclose"), ('FE', 'Female'), ('MA', 'Male')], default='NO', max_length=2)),
                ('numberOfChildren', models.IntegerField(default=2)),
                ('isRegular', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 12, 5, 46, 148838, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower'), ('CL', 'Childcare Permanent'), ('BA', 'Babysitting')], default='AC', max_length=2),
        ),
    ]
