# Generated by Django 3.0.7 on 2022-04-01 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_auto_20220401_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcareofferlongterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='childcareoffershortterm',
            name='id',
        ),
        migrations.AddField(
            model_name='childcareofferlongterm',
            name='genericOffer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcareoffershortterm',
            name='genericOffer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 12, 8, 35, 14021, tzinfo=utc), verbose_name='date published'),
        ),
    ]
