# Generated by Django 3.0.7 on 2022-04-01 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_auto_20220401_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareOffer',
            fields=[
                ('genericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
                ('helpType', models.CharField(choices=[('ELD', 'Elderly Care'), ('DIS', 'Care for handicapped People'), ('PSY', 'Psychological Aid')], default='CAR', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 14, 34, 25, 993366, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower'), ('CL', 'Childcare Permanent'), ('BA', 'Babysitting'), ('WE', 'Medical Assistance')], default='AC', max_length=2),
        ),
    ]
