# Generated by Django 3.0.7 on 2022-04-01 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_auto_20220401_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='childcareoffershortterm',
            old_name='numberOfChildren',
            new_name='numberOfChildrenToCare',
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='numberOfChildren',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='numberOfPets',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 14, 57, 4, 29251, tzinfo=utc), verbose_name='date published'),
        ),
    ]
