# Generated by Django 3.0.7 on 2022-04-01 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_auto_20220401_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='id',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='genericOffer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(choices=[('ACA', 'Academic Support'), ('ADM', 'Administration'), ('ADV', 'Advancement'), ('CON', 'Conference and Events'), ('FAC', 'Facility Operations'), ('FIN', 'Finance and Accounting'), ('GEN', 'General Administration'), ('HEA', 'Health Services'), ('HUM', 'Human Resources'), ('INF', 'Information Technology'), ('INT', 'International Program and Services'), ('LEG', 'Legal'), ('LIB', 'Library Administration'), ('MAR', 'Marketing, Communication and External Affairs'), ('OFF', 'Office and Admin Support'), ('PER', 'Performing Arts and Museum Administration'), ('PUB', 'Public Safety'), ('RES', 'Research and Program Admin'), ('SPO', 'Sports and Recreation'), ('STU', 'Student Services'), ('HAN', 'Handicraft profession')], default='ACA', max_length=3),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 17, 0, 13, 669598, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower'), ('CL', 'Childcare Permanent'), ('BA', 'Babysitting'), ('WE', 'Medical Assistance'), ('JO', 'Job')], default='AC', max_length=2),
        ),
    ]
