# Generated by Django 3.0.7 on 2022-04-02 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_auto_20220402_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonnationOffer',
            fields=[
                ('account', models.CharField(max_length=350)),
                ('donnationTitle', models.CharField(blank=True, max_length=128)),
                ('genericOffer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.GenericOffer')),
            ],
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 1, 4, 35, 29695, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower'), ('CL', 'Childcare Permanent'), ('BA', 'Babysitting'), ('WE', 'Medical Assistance'), ('JO', 'Job'), ('DO', 'Donnation')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='welfareoffer',
            name='helpType',
            field=models.CharField(choices=[('ELD', 'Elderly Care'), ('DIS', 'Care for handicapped People'), ('PSY', 'Psychological Aid')], default='ELD', max_length=3),
        ),
    ]
