# Generated by Django 3.0.7 on 2022-04-02 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_auto_20220402_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationoffer',
            name='typeOfCar',
        ),
        migrations.AddField(
            model_name='transportationoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 14, 2, 11, 321144)),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='startDateAccomodation',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 14, 2, 11, 319979)),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('HO', 'Whole Flat / House'), ('RO', 'Private Room'), ('SO', 'Sofa / Bed')], default='SO', max_length=2, verbose_name={('HO', 'Whole Flat / House'), ('RO', 'Private Room'), ('SO', 'Sofa / Bed')}),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 14, 2, 11, 315513, tzinfo=utc), verbose_name='date published'),
        ),
    ]
