# Generated by Django 3.0.7 on 2022-04-03 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0028_auto_20220402_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationoffer',
            name='startDateAccomodation',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 11, 59, 5, 608403)),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 11, 59, 5, 604821, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 11, 59, 5, 609278)),
        ),
    ]
