# Generated by Django 3.0.7 on 2022-04-03 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_auto_20220403_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonnationOffer',
            new_name='DonationOffer',
        ),
        migrations.RenameField(
            model_name='donationoffer',
            old_name='donnationTitle',
            new_name='donationTitle',
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='endDateAccomodation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='startDateAccomodation',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 12, 56, 48, 98704)),
        ),
        migrations.AlterField(
            model_name='accomodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Private Room'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 12, 56, 48, 94966, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Accomodation'), ('TL', 'Translation'), ('TR', 'Transportation'), ('BU', 'Buerocratic'), ('MP', 'Manpower'), ('CL', 'Childcare Permanent'), ('BA', 'Babysitting'), ('WE', 'Medical Assistance'), ('JO', 'Job'), ('DO', 'Donation')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 12, 56, 48, 99619)),
        ),
    ]
