# Generated by Django 3.0.7 on 2022-04-03 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0032_auto_20220403_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='startDateAccommodation',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 17, 28, 2, 261165)),
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('HO', 'Whole Flat / House'), ('RO', 'Private Room'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 17, 28, 2, 258015, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 17, 28, 2, 261902)),
        ),
    ]
