# Generated by Django 3.0.7 on 2022-04-04 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_auto_20220403_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='startDateAccommodation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('HO', 'Whole Flat / House'), ('RO', 'Private Room'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
