# Generated by Django 3.0.7 on 2022-04-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220331_0723'),
        ('offers', '0035_auto_20220404_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('HO', 'Whole Flat / House'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='firstLanguage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firstLanguage', to='accounts.Languages'),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='secondLanguage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondLanguage', to='accounts.Languages'),
        ),
    ]
