# Generated by Django 3.0.7 on 2022-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0038_auto_20220404_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='country',
            field=models.CharField(choices=[('DE', 'Deutschland'), ('PL', 'Polen'), ('AT', 'Österreich')], default='DE', max_length=2),
        ),
    ]
