# Generated by Django 3.0.7 on 2022-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0039_auto_20220404_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('HO', 'Whole Flat / House'), ('SO', 'Sofa / Bed'), ('RO', 'Private Room')], default='SO', max_length=2),
        ),
    ]
