# Generated by Django 3.0.7 on 2022-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0039_auto_20220404_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('HO', 'Whole Flat / House'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='firstLanguage',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='secondLanguage',
            field=models.CharField(max_length=2),
        ),
    ]
