# Generated by Django 3.0.7 on 2022-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0040_auto_20220404_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
    ]
