# Generated by Django 3.0.7 on 2022-04-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0041_auto_20220404_1402'),
        ('offers', '0041_auto_20220404_1344'),
    ]

    operations = [
    ]
