# Generated by Django 3.0.7 on 2022-04-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0042_merge_20220405_0817'),
        ('offers', '0042_merge_20220404_1648'),
    ]

    operations = [
    ]
