# Generated by Django 3.0.7 on 2022-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0043_merge_20220406_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcareofferlongterm',
            old_name='gender',
            new_name='gender_longterm',
        ),
        migrations.RenameField(
            model_name='childcareoffershortterm',
            old_name='gender',
            new_name='gender_shortterm',
        ),
    ]
