# Generated by Django 3.0.7 on 2022-04-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0043_auto_20220404_2151'),
        ('offers', '0042_merge_20220405_0817'),
    ]

    operations = [
    ]
