# Generated by Django 3.0.7 on 2022-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0044_auto_20220406_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buerocraticoffer',
            old_name='helpType',
            new_name='helpType_buerocratic',
        ),
        migrations.RenameField(
            model_name='manpoweroffer',
            old_name='helpType',
            new_name='helpType_manpower',
        ),
        migrations.RenameField(
            model_name='welfareoffer',
            old_name='helpType',
            new_name='helpType_welfare',
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Private Room'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
    ]
