# Generated by Django 3.0.7 on 2022-04-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0042_merge_20220404_1501'),
        ('offers', '0044_merge_20220405_1231'),
        ('offers', '0045_auto_20220406_1205'),
        ('offers', '0042_merge_20220404_2024'),
    ]

    operations = [
    ]
