# Generated by Django 3.0.7 on 2022-04-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220412_0701'),
        ('offers', '0046_merge_20220408_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='childcareofferlongterm',
            name='gender_longterm',
            field=models.CharField(choices=[('NO', "Don't want to disclose"), ('FE', 'Female'), ('MA', 'Male'), ('OT', 'Other')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='childcareoffershortterm',
            name='gender_shortterm',
            field=models.CharField(choices=[('NO', "Don't want to disclose"), ('FE', 'Female'), ('MA', 'Male'), ('OT', 'Other')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='country',
            field=models.CharField(choices=[('', 'Land wählen'), ('DE', 'Deutschland'), ('PL', 'Polen'), ('AT', 'Österreich')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='firstLanguage',
            field=models.ForeignKey(default='de', on_delete=django.db.models.deletion.CASCADE, related_name='firstLanguage', to='accounts.Languages'),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='secondLanguage',
            field=models.ForeignKey(default='uk', on_delete=django.db.models.deletion.CASCADE, related_name='secondLanguage', to='accounts.Languages'),
        ),
    ]
