# Generated by Django 3.0.7 on 2022-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0047_auto_20220412_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House'), ('RO', 'Private Room')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerDescription',
            field=models.TextField(blank=True),
        ),
    ]
