# Generated by Django 3.0.7 on 2022-04-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0048_auto_20220412_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='bb',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericoffer',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerDescription',
            field=models.TextField(),
        ),
    ]
