# Generated by Django 3.0.7 on 2022-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0049_auto_20220412_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericoffer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='genericoffer',
            name='postCode',
        ),
        migrations.RemoveField(
            model_name='genericoffer',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='genericoffer',
            name='streetNumber',
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Private Room'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
    ]
