# Generated by Django 3.0.7 on 2022-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0050_auto_20220412_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='location',
            field=models.TextField(default='Berlin', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House'), ('RO', 'Private Room')], default='SO', max_length=2),
        ),
    ]
