# Generated by Django 3.0.7 on 2022-04-13 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0053_auto_20220412_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationoffer',
            name='postCodeEnd',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='streetNameEnd',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='streetNumberEnd',
        ),
        migrations.AddField(
            model_name='transportationoffer',
            name='latEnd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationoffer',
            name='lngEnd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationoffer',
            name='locationEnd',
            field=models.TextField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Private Room'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='userId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
