# Generated by Django 3.0.7 on 2022-04-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0054_auto_20220413_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationoffer',
            name='bbEnd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('HO', 'Whole Flat / House'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
    ]
