# Generated by Django 3.0.7 on 2022-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0055_auto_20220413_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='bbEnd',
            field=models.CharField(max_length=300),
        ),
    ]
