# Generated by Django 3.0.7 on 2022-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0056_auto_20220413_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Private Room'), ('HO', 'Whole Flat / House'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
    ]
