# Generated by Django 3.0.7 on 2022-04-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0057_auto_20220413_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('HO', 'Whole Flat / House'), ('RO', 'Private Room')], default='SO', max_length=2),
        ),
    ]
