# Generated by Django 3.0.7 on 2022-04-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220412_0701'),
        ('offers', '0060_auto_20220415_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('HO', 'Gesamte Wohnung / Haus'), ('RO', 'Eigener Raum'), ('SO', 'Sofa / Bed')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='buerocraticoffer',
            name='helpType_buerocratic',
            field=models.CharField(choices=[('AM', 'Begleitung'), ('LE', 'Juristische Hilfe'), ('OT', 'Andere')], default='AM', max_length=2),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(choices=[('ACA', 'Akademische Hilfe,'), ('ADM', 'Administration,'), ('ADV', 'Fortbildung,'), ('CON', 'Konferenzen und Events,'), ('FAC', 'Anlagenbetrieb,'), ('FIN', 'Finance und Buchhaltung,'), ('GEN', 'Allgemeine Verwaltung,'), ('HEA', 'Gesundheitsservices,'), ('HUM', 'Personalwesen,'), ('INF', 'IT,'), ('INT', 'International Program and Services,'), ('LEG', 'Jura,'), ('LIB', 'BÜchereiverwaltung,'), ('MAR', 'Marketing,'), ('OFF', 'Büro / Verwaltung,'), ('PER', 'Kunst und Museumsverwaltung,'), ('PUB', 'Öffentliche Sicherheit,'), ('RES', 'Forschung und Forschungsadministration,'), ('SPO', 'Sport,'), ('STU', 'Studentische Dienstleistungen,'), ('HAN', 'Handwerk')], default='ACA', max_length=3),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='helpType_manpower',
            field=models.CharField(choices=[('ON', 'Online'), ('OS', 'Vor Ort')], default='ON', max_length=2),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='firstLanguage',
            field=models.ForeignKey(default='de', on_delete=django.db.models.deletion.CASCADE, related_name='firstLanguage', to='accounts.Languages', verbose_name='Erste Sprache'),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='secondLanguage',
            field=models.ForeignKey(default='uk', on_delete=django.db.models.deletion.CASCADE, related_name='secondLanguage', to='accounts.Languages', verbose_name='Zweite Sprache'),
        ),
    ]
