# Generated by Django 3.0.7 on 2022-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0062_auto_20220419_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationoffer',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='accommodationoffer',
            name='streetNumber',
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('RO', 'Eigener Raum'), ('SO', 'Sofa / Bed'), ('HO', 'Gesamte Wohnung / Haus')], default='SO', max_length=2),
        ),
    ]
