# Generated by Django 3.0.7 on 2022-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0063_auto_20220419_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Eigener Raum'), ('HO', 'Gesamte Wohnung / Haus')], default='SO', max_length=2),
        ),
    ]
