# Generated by Django 3.0.7 on 2022-04-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0064_auto_20220421_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationoffer',
            name='endDateAccommodation',
        ),
    ]
