# Generated by Django 3.0.7 on 2022-04-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0065_remove_accommodationoffer_enddateaccommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericoffer',
            name='requestForHelp',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(choices=[('ACA', 'Akademische Hilfe'), ('ADM', 'Administration'), ('ADV', 'Fortbildung'), ('CON', 'Konferenzen und Events'), ('FAC', 'Anlagenbetrieb'), ('FIN', 'Finance und Buchhaltung'), ('GEN', 'Allgemeine Verwaltung'), ('HEA', 'Gesundheitsservices'), ('HUM', 'Personalwesen'), ('INF', 'IT'), ('INT', 'International Program and Services'), ('LEG', 'Jura'), ('LIB', 'BÜchereiverwaltung'), ('MAR', 'Marketing'), ('OFF', 'Büro / Verwaltung'), ('PER', 'Kunst und Museumsverwaltung'), ('PUB', 'Öffentliche Sicherheit'), ('RES', 'Forschung und Forschungsadministration'), ('SPO', 'Sport'), ('STU', 'Studentische Dienstleistungen'), ('HAN', 'Handwerk')], default='ACA', max_length=3),
        ),
    ]
