# Generated by Django 3.0.7 on 2022-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0066_auto_20220423_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationoffer',
            old_name='numberOfAdults',
            new_name='numberOfPeople',
        ),
        migrations.RemoveField(
            model_name='accommodationoffer',
            name='numberOfChildren',
        ),
        migrations.RemoveField(
            model_name='accommodationoffer',
            name='numberOfPets',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='bbEnd',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='latEnd',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='lngEnd',
        ),
        migrations.RemoveField(
            model_name='transportationoffer',
            name='locationEnd',
        ),
        migrations.AddField(
            model_name='accommodationoffer',
            name='petsAllowed',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transportationoffer',
            name='distance',
            field=models.IntegerField(default=100),
        ),
    ]
