# Generated by Django 3.0.7 on 2022-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0067_auto_20220426_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationoffer',
            name='helpType_transport',
            field=models.CharField(choices=[('PT', 'Personentransport'), ('GT', 'Gütertransport')], default='PT', max_length=2),
        ),
    ]
