# Generated by Django 3.0.7 on 2022-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0070_auto_20220426_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpoweroffer',
            name='helpType_manpower',
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='canGoforeign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='describeMedicalExperience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='distanceChoices',
            field=models.CharField(choices=[('0', '0-100km'), ('1', '100-200km'), ('2', '200-400km'), ('3', '400-600km'), ('4', 'Komplett Flexibel')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='hasDriverslicense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='hasExperience_crisis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpoweroffer',
            name='hasMedicalExperience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welfareoffer',
            name='hasEducation_welfare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welfareoffer',
            name='typeOfEducation',
            field=models.TextField(default=''),
        ),
    ]
