# Generated by Django 3.0.7 on 2022-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220420_1358'),
        ('offers', '0071_auto_20220426_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationoffer',
            name='firstLanguage',
        ),
        migrations.RemoveField(
            model_name='translationoffer',
            name='secondLanguage',
        ),
        migrations.AddField(
            model_name='translationoffer',
            name='languages',
            field=models.ManyToManyField(blank=True, to='accounts.Languages', verbose_name='Sprachen'),
        ),
    ]
