# Generated by Django 3.0.7 on 2022-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0073_auto_20220427_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerocraticoffer',
            name='helpType_buerocratic',
            field=models.CharField(choices=[('AM', 'Begleitung'), ('LE', 'Juristische Hilfe'), ('OT', 'Andere Bürokratische Hilfe')], default='AM', max_length=2),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Unterbringung'), ('TL', 'Übersetzung'), ('TR', 'Logistik'), ('BU', 'Bürokratie'), ('MP', 'Manneskraft'), ('CL', 'Kinderbetreuung'), ('WE', 'Medizinische Hilfe'), ('JO', 'Jobangebot')], default='AC', max_length=2),
        )
    ]
