# Generated by Django 3.0.7 on 2022-05-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0075_auto_20220512_1056'),
        ('offers', '0075_auto_20220512_0950'),
    ]

    operations = [
    ]
