# Generated by Django 3.0.7 on 2022-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0077_auto_20220513_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoffer',
            name='bb',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='location',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerTitle',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='describeMedicalExperience',
            field=models.TextField(default=' '),
        ),
    ]
