# Generated by Django 3.0.7 on 2022-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0078_auto_20220513_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Unterbringung'), ('TL', 'Übersetzung'), ('TR', 'Logistik'), ('BU', 'Bürokratie'), ('MP', 'Hilfe vor Ort'), ('CL', 'Kinderbetreuung'), ('WE', 'Medizinische Hilfe'), ('JO', 'Jobangebot')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='describeMedicalExperience',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='welfareoffer',
            name='typeOfEducation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
