# Generated by Django 3.0.7 on 2022-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0080_auto_20220513_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoffer',
            name='offerTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
