# Generated by Django 3.0.7 on 2022-05-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0080_auto_20220513_1305'),
        ('offers', '0074_auto_20220510_1025'),
    ]

    operations = [
    ]
