# Generated by Django 3.0.7 on 2022-05-28 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_lastconfirmationmailsent'),
        ('offers', '0081_auto_20220514_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoffer',
            name='numberOfPeople',
            field=models.IntegerField(default=2, verbose_name='Anzahl Personen'),
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='petsAllowed',
            field=models.BooleanField(blank=True, default=0, verbose_name='Haustiere erlaubt'),
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='startDateAccommodation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Startdatum der Unterbringung'),
        ),
        migrations.AlterField(
            model_name='accommodationoffer',
            name='typeOfResidence',
            field=models.CharField(choices=[('SO', 'Sofa / Bed'), ('RO', 'Eigener Raum'), ('HO', 'Gesamte Wohnung / Haus')], default='SO', max_length=2, verbose_name='Art der Unterkunft'),
        ),
        migrations.AlterField(
            model_name='buerocraticoffer',
            name='helpType',
            field=models.CharField(choices=[('AM', 'Begleitung'), ('LE', 'Juristische Hilfe'), ('OT', 'Andere Bürokratische Hilfe')], default='AM', max_length=2, verbose_name='Art der Hilfe'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='distance',
            field=models.IntegerField(default=5, verbose_name='Entfernung'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='hasEducation',
            field=models.BooleanField(default=False, verbose_name='Hat Ausbildung'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='hasExperience',
            field=models.BooleanField(default=False, verbose_name='Hat Erfahrung'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='hasSpace',
            field=models.BooleanField(default=False, verbose_name='Hat Räumlichkeiten'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='helpType_childcare',
            field=models.CharField(choices=[('GT', 'Ganztagsbetreuung'), ('HT', 'Halbtagsbetreuung'), ('WE', 'Wochendendsbetreuung')], default='GT', max_length=2, verbose_name='Art der Betreuung'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='isRegular',
            field=models.BooleanField(default=False, verbose_name='Ist regulär'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='numberOfChildren',
            field=models.IntegerField(default=1, verbose_name='Anzahl Kinder'),
        ),
        migrations.AlterField(
            model_name='childcareoffer',
            name='timeOfDay',
            field=models.CharField(choices=[('VM', 'Vormittags'), ('NM', 'Nachmittags'), ('AB', 'Abends')], default='VM', max_length=2, verbose_name='Tageszeit'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ist aktiv'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='incomplete',
            field=models.BooleanField(default=False, verbose_name='Ist unvollständig'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='isDigital',
            field=models.BooleanField(default=False, verbose_name='Ist digital'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='location',
            field=models.TextField(default='', max_length=300, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerDescription',
            field=models.TextField(default='', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerTitle',
            field=models.CharField(default='', max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='offerType',
            field=models.CharField(choices=[('AC', 'Unterbringung'), ('TL', 'Übersetzung'), ('TR', 'Logistik'), ('BU', 'Bürokratie'), ('MP', 'Hilfe vor Ort'), ('CL', 'Kinderbetreuung'), ('WE', 'Medizinische Hilfe'), ('JO', 'Jobangebot')], default='AC', max_length=2, verbose_name='Angebotstyp'),
        ),
        migrations.AlterField(
            model_name='genericoffer',
            name='requestForHelp',
            field=models.BooleanField(default=False, editable=False, verbose_name='Ist Hilfsanfrage'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=128, verbose_name='Jobtitel'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='jobType',
            field=models.CharField(choices=[('ACA', 'Akademische Hilfe'), ('ADM', 'Administration'), ('ADV', 'Fortbildung'), ('CON', 'Konferenzen und Events'), ('FAC', 'Anlagenbetrieb'), ('FIN', 'Finance und Buchhaltung'), ('GEN', 'Allgemeine Verwaltung'), ('HEA', 'Gesundheitsservices'), ('HUM', 'Personalwesen'), ('INF', 'IT'), ('INT', 'International Program and Services'), ('LEG', 'Jura'), ('LIB', 'BÜchereiverwaltung'), ('MAR', 'Marketing'), ('OFF', 'Büro / Verwaltung'), ('PER', 'Kunst und Museumsverwaltung'), ('PUB', 'Öffentliche Sicherheit'), ('RES', 'Forschung und Forschungsadministration'), ('SPO', 'Sport'), ('STU', 'Studentische Dienstleistungen'), ('HAN', 'Handwerk')], default='ACA', max_length=3, verbose_name='Art des Jobs'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Anforderungen'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='canGoforeign',
            field=models.BooleanField(default=False, verbose_name='Auslandseinsatz möglich'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='describeMedicalExperience',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung medizinische Erfahrung'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='distanceChoices',
            field=models.CharField(choices=[('1', '0-50km'), ('1', '50-100km'), ('2', '100-200km'), ('3', '200-400km'), ('4', '400-600km'), ('5', 'Komplett Flexibel')], default='0', max_length=1, verbose_name='Entfernung'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='hasDriverslicense',
            field=models.BooleanField(default=False, verbose_name='Hat Fahrerlaubnis'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='hasExperience_crisis',
            field=models.BooleanField(default=False, verbose_name='Erfahrung mit Krisenmanagement'),
        ),
        migrations.AlterField(
            model_name='manpoweroffer',
            name='hasMedicalExperience',
            field=models.BooleanField(default=False, verbose_name='Hat medizinische Erfahrung'),
        ),
        migrations.AlterField(
            model_name='translationoffer',
            name='languages',
            field=models.ManyToManyField(blank=True, through='offers.LanguageOfferMap', to='accounts.Languages', verbose_name='Übersetzte Sprachen'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='distance',
            field=models.IntegerField(default=100, verbose_name='Entfernung'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='helpType',
            field=models.CharField(choices=[('PT', 'Personentransport'), ('GT', 'Gütertransport')], default='PT', max_length=2, verbose_name='Art des Transports'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='numberOfPassengers',
            field=models.IntegerField(default=2, verbose_name='Anzahl freier Plätze'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='typeOfCar',
            field=models.CharField(choices=[('KW', 'Kleinwagen'), ('MW', 'Mittelklassewagen'), ('KM', 'Kombi'), ('SU', 'SUV'), ('MI', 'Minivan'), ('TR', 'Transporter')], default='KW', max_length=2, verbose_name='Fahrzeugtyp'),
        ),
        migrations.AlterField(
            model_name='welfareoffer',
            name='hasEducation_welfare',
            field=models.BooleanField(default=False, verbose_name='Hat Vorerfahrung'),
        ),
        migrations.AlterField(
            model_name='welfareoffer',
            name='helpType',
            field=models.CharField(choices=[('ELD', 'Altenpflege'), ('DIS', 'Behindertenpflege'), ('PSY', 'Psychologische Hilfe')], default='ELD', max_length=3, verbose_name='Art der Hilfe'),
        ),
        migrations.AlterField(
            model_name='welfareoffer',
            name='typeOfEducation',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung der Erfahrung'),
        ),
        migrations.DeleteModel(
            name='DonationOffer',
        ),
    ]
