# Generated by Django 3.0.7 on 2022-06-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0081_merge_20220513_1743'),
        ('offers', '0081_auto_20220514_1302'),
    ]

    operations = [
    ]
