# Generated by Django 3.0.7 on 2022-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0082_auto_20220528_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpoweroffer',
            name='distanceChoices',
            field=models.CharField(choices=[('0', '0-50km'), ('1', '50-100km'), ('2', '100-200km'), ('3', '200-400km'), ('4', '400-600km'), ('5', 'Komplett Flexibel')], default='0', max_length=1, verbose_name='Entfernung'),
        ),
        migrations.AlterField(
            model_name='transportationoffer',
            name='distance',
            field=models.CharField(choices=[('0', '0-50km'), ('1', '50-100km'), ('2', '100-200km'), ('3', '200-400km'), ('4', '400-600km'), ('5', 'Komplett Flexibel')], default='0', max_length=1, verbose_name='Entfernung (Bereit zu fahren)'),
        ),
    ]
