# Generated by Django 3.0.7 on 2022-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0085_auto_20220608_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcareoffer',
            name='distance',
            field=models.CharField(choices=[('0', '5km'), ('1', '10km'), ('2', '20km'), ('3', '50km')], default='0', max_length=1, verbose_name='Maximale Entfernung'),
        ),
    ]
