# Generated by Django 3.0.7 on 2022-03-22 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamorganisation', '0002_auto_20220322_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='approvedBy',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
