# Generated by Django 3.0.7 on 2022-04-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0005_auto_20220331_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(default=5)),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=100000)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='iamorganisation.Organisation')),
            ],
        ),
    ]
