# Generated by Django 3.0.7 on 2022-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0006_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='recipientCount',
            field=models.IntegerField(default=0),
        ),
    ]
