# Generated by Django 3.0.7 on 2022-04-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0007_helprequest_recipientcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='appearsInMap',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='clubNumber',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='generalInfo',
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=models.CharField(choices=[('', 'Land wählen'), ('DE', 'Deutschland'), ('PL', 'Polen'), ('AT', 'Österreich')], max_length=50),
        ),
    ]
