# Generated by Django 3.0.7 on 2022-04-20 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamorganisation', '0008_auto_20220412_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='acceptedDataSharing',
            field=models.BooleanField(default=False, verbose_name='Datenweitergabeerklärung akzeptiert'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='acceptedPrivacyStatement',
            field=models.BooleanField(default=False, verbose_name='Datenschutzerklärung akzeptiert'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='approvedBy',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedBy', to=settings.AUTH_USER_MODEL, verbose_name='Approved von'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contactPerson',
            field=models.CharField(default='', max_length=100, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisationName',
            field=models.CharField(default='', max_length=300, verbose_name='Name der Organisation'),
        ),
    ]
