# Generated by Django 3.0.7 on 2022-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0009_auto_20220420_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='about',
            field=models.TextField(default='', max_length=500000, verbose_name='Über uns'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_logos/'),
        ),
    ]
