# Generated by Django 3.0.7 on 2022-04-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0010_auto_20220421_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=100000)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='iamorganisation.Organisation')),
            ],
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='title',
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iamorganisation.Request')),
                ('donationGoal', models.IntegerField(null=True)),
            ],
            bases=('iamorganisation.request',),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='request_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iamorganisation.Request'),
            preserve_default=False,
        ),
    ]
