# Generated by Django 3.0.7 on 2022-04-23 17:28

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0013_auto_20220423_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='beneficiary',
            field=models.CharField(default='', max_length=70, verbose_name='Begünstigte/r'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='iban',
            field=localflavor.generic.models.IBANField(default=0, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='reason',
            field=models.CharField(default='', max_length=140, verbose_name='Spendenstichwort'),
            preserve_default=False,
        ),
    ]
