# Generated by Django 3.0.7 on 2022-04-25 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0014_auto_20220423_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
    ]
