# Generated by Django 3.0.7 on 2022-04-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0015_request_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='donationGoal',
        ),
    ]
