# Generated by Django 3.0.7 on 2022-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0016_remove_donationrequest_donationgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='bb',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
