# Generated by Django 3.0.7 on 2022-04-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0017_auto_20220426_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDonationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iamorganisation.Request')),
                ('location', models.CharField(default='', max_length=1000)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('bb', models.CharField(default='', max_length=300)),
            ],
            bases=('iamorganisation.request',),
        ),
    ]
