# Generated by Django 3.0.7 on 2022-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamorganisation', '0018_materialdonationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdonationrequest',
            name='donationType',
            field=models.CharField(default='', max_length=500),
        ),
    ]
