# Generated by Django 3.0.7 on 2022-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='favouriteOffers',
            field=models.ManyToManyField(related_name='favouritedBy', to='offers.GenericOffer'),
        ),
    ]
