# Generated by Django 3.0.7 on 2022-04-03 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_auto_20220403_2325'),
        ('ineedhelp', '0002_refugee_favouriteoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedIntermediary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateViewed', models.DateTimeField(default=datetime.datetime(2022, 4, 3, 23, 25, 7, 349570, tzinfo=utc))),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.GenericOffer')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ineedhelp.Refugee')),
            ],
        ),
        migrations.AddField(
            model_name='refugee',
            name='recentlyViewedOffers',
            field=models.ManyToManyField(related_name='recentlyViewedBy', through='ineedhelp.RecentlyViewedIntermediary', to='offers.GenericOffer'),
        ),
    ]
