# Generated by Django 3.0.7 on 2022-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ineedhelp', '0003_auto_20220403_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedintermediary',
            name='dateViewed',
            field=models.DateTimeField(),
        ),
    ]
