# Generated by Django 3.0.7 on 2022-04-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0060_auto_20220415_0851'),
        ('ineedhelp', '0004_auto_20220404_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyContactedIntermediary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateContacted', models.DateTimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.GenericOffer')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ineedhelp.Refugee')),
            ],
        ),
        migrations.AddField(
            model_name='refugee',
            name='recentlyContactedOffers',
            field=models.ManyToManyField(related_name='recentlyContactedBy', through='ineedhelp.RecentlyContactedIntermediary', to='offers.GenericOffer'),
        ),
    ]
