name: Deploy to Prod
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy on Prod Server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: sh /home/cscharfstein/periodic.sh
